#!/usr/bin/env python3

import sys
import os

options = ('shutdown', 'sleep', 'hibernate', 'log out', 'reboot', 'boot to bios')

text = {
    'shutdown': 'Shut down',
    'sleep': 'Sleep',
    'hibernate': 'Hibernate',
    'log out': 'Log out',
    'reboot': 'Reboot',
    'boot to bios': 'Boot to bios'
}

icons = {
    'shutdown': '\u23fb',
    'sleep': '\u23fe',
    'hibernate': '\U0001f5b4',
    'log out': '\U0001f872\u20de',
    'reboot': '\u2b6e ',
    'boot to bios': '\U0001f527\ufe0e'
}

actions = {
    'shutdown': 'systemctl poweroff',
    'sleep': 'systemctl suspend',
    'hibernate': 'systemctl hibernate',
    'log out': 'i3-msg exit',
    'reboot': 'systemctl reboot',
    'boot to bios': 'systemctl reboot --firmware-setup'
}

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print("\0prompt\x1fPower menu")
        for option in options:
            print(icons[option], text[option], '\0info\x1f', actions[option])
    else:
        action = os.getenv('ROFI_INFO')
        os.system(action)

